# Config can also be as a JSON file
project:
    name: "Lyra" # Should be the same as `.uproject` file name
    path: "C:/repos/Lyra" # Path to root of the project (where `.uproject` file is)

engine:
    path: "C:/UnrealEngine/UE5.4" # Path to root of Unreal Engine

build:
    outputPath: "C:/BuildArtifacts"
    override: null # 0-based index of which target to build (can be an array of targets). null (or removed) for all
    additionalCookerOptions: null # Any additional options to pass to Unreal's cooker (e.g. command line overrides for config values). Should be a single string, e.g. "-ini:Engine:[/Script/UnrealEd.ProjectPackagingSettings]FullRebuild=true"
    targets:
        -   platform: Win64
            target: LyraGame
            configuration: DebugGame
            deploy:
                steam:
                    steamcmdPath: "C:/steamcmd.exe"  # Path to `steamcmd` executable
                    appID: 480  # Steam game's AppID
                    depotID: 1000  # Steam depot ID to upload to
                    auth:  # Auth information for a user that is allowed to upload build to this AppID
                        user: "steam_username"
                        password: "steam_password"
                        steamGuard: true  # If true, you will be prompted to enter Steam Guard code during deployment
                    testDeployment: true  # Whether to actually perform the deployment, or just run a test
                    liveBranch: "alpha"  # Optional: set this uploaded build live on the specified branch
        -   platform: Linux
            target: LyraServer
            configuration: Shipping
            clangToolchainPath: "C:/UnrealToolchains/v22_clang-16.0.6-centos7/x86_64-unknown-linux-gnu" # Optional. Overrides LINUX_MULTIARCH_ROOT only for this target build
            deploy:
                remoteCopy: # Run SCP to copy build to a remote server
                    host: 1.2.3.4  # server IP or domain
                    user: ec2-root
                    destinationPath: "/home/ec2-root/LinuxServer"
                    certificatePath: "C:/private-key.pem"
                    killTarget: "MyGameServer"
                awsEC2:
                    instanceID: "i-0e8fffffff"
                    user: "ec2-user"
                    destinationPath: "/home/ec2-root/LinuxServer"
                    certificatePath: "C:/private-key.pem"
                    killTarget: "MyGameServer"
                docker:
                    image: "lyra-docker-image"  # Should be full URL if you want to push to a registry
                    tag: "latest"
                    push: false
                awsGameLiftContainers:
                    image: "my-repo/my-game-server"
                    tag: "latest"
                    push: true
                    containerGroupDefinitionName: "MyGameServerGroup"
                    managedContainerFleetId: "fleet-12345678-1234-1234-1234-123456789012"
                    region: "us-east-1"

vcs:
    enabled: false
    git:
        branch: ""  # Default is the current branch
    perforce:
        workspace: ""
        username: ""
        password: ""
