# Config can also be as a JSON file
project:
    name: "Lyra" # Should be the same as `.uproject` file name
    path: "C:/repos/Lyra" # Path to root of the project (where `.uproject` file is)

engine:
    path: "C:/UnrealEngine/UE5.4" # Path to root of Unreal Engine

build:
    outputPath: "C:/BuildArtifacts"
    targets:
        -   platform: Win64
            target: LyraGame
            configuration: DebugGame
        -   platform: Linux
            target: LyraServer
            configuration: Shipping
            deploy:
                remoteCopy: # Run SCP to copy build to a remote server
                    host: 1.2.3.4  # server IP or domain
                    user: ec2-root
                    destinationPath: "/home/ec2-root/LinuxServer"
                    certificatePath: "C:/private-key.pem"
    override: null # 0-based index of which target to build (can be an array of targets). null (or removed) for all

vcs:
    enabled: false
    git:
        repository: ""
    perforce:
        workspace: ""
        username: ""
        password: ""
